### ISSUE TITLE
Dose differences in L1000 and Cell Painting

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-profiling-comparison#9]
The column identifying dose in the [LINCS Cell Painting](https://github.com/broadinstitute/lincs-cell-painting) dataset is `Metadata_mmoles_per_liter`. However, the compound dose used in the L1000 set (column name `pert_idose`) is in "uM" units. Typically, mmoles means millimolar and uM means micromolar. 1 uM = 0.001 mM.

Are the compound doses not aligned between the datasets? Or, does `mmoles_per_liter` mean micromolar?

**Comment by gwaygenomics** [comment]
One strategy to answer this question is to use the `mg_per_ml` column since "mg" and "ml" are more standard in some ways.

Using compound molarity, I can convert one column to the other and determine if the conversion factor is `uM` or `mM`. I tried this with the first two compounds in [this document](https://github.com/broadinstitute/lincs-cell-painting/blob/master/metadata/platemaps/2016_04_01_a549_48hr_batch1/platemap/C-7161-01-LM6-001.txt)

## Example 1: BRD-K25114078-003-08-1

pert_iname: aminoguanidine
Expected molarity: 74.059
mg_per_ml: 1.10546000000000006
mmoles_per_liter: 9.99999999999999999

### Conversion

Step 1: 1.105 mg/ml = 1105 mg/L = 1.105 g/L
Step 2: 1.105 g/L / 74.059 g/mole =0.0149 moles / L 

0.0149 moles / L = 14.9 mmoles / L = 14,900 umoles / L

This does not align with the given `mmoles_per_liter` above, but it is on the same scale as mmoles.

## Example 2: BRD-K25140590-001-03-0

pert_iname: CX-516
Expected molarity: 233.105
mg_per_ml: 2.33263100000000008
mmoles_per_liter: 9.99999999999999999

### Conversion

Step 1: 2.333 mg/ml = 2.333 mg/L = 2.333 g/L
Step 2: 2.333 g/L / 233.105 g/mole = 0.010008 moles / L 

0.010008 moles / L = 10.008 mmoles / L = 10,008 umoles / L

This is within rounding error of the provided mmoles (millimoles)

**Comment by gwaygenomics** [comment]
My conclusion is that mmoles_per_liter means millimoles. The next thing to check is if the L1000 dataset is actually measuring in micromoles

**Comment by AnneCarpenter** [comment]
Sometimes concentrations as a column heading reflect the compound source concentration and sometimes they reflect the actual treatment concentration. It may be the source of confusion/discrepancy here. Hopefully Shantanu can add some concrete detail because I hope he recalls this.

**Comment by gwaygenomics** [comment]
For completeness, we cleared this issue up in slack:

> compound source concentration and sometimes they reflect the actual treatment concentration

This is the missing step:

0.37mM * 0.05uL / 50uL = 0.37uM

0.05 uL is the volume of compound added to the total well volume of 50uL.
